=== akatzke/HerediClassify/API/schema_input.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "chr": {
      "type": "string"
    },
    "pos": {
      "type": "integer"
    },
    "gene": {
      "type": "string"
    },
    "ref": {
      "type": "string"
    },
    "alt": {
      "type": "string"
    },
    "variant_type": {
      "type": "array",
      "minItems" : 1,
      "items": {"type" : "string"}
    },
    "variant_effect": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "transcript": {
              "type": "string",
              "pattern" : "ENST[0-9]{5,15}"
            },
            "hgvs_c": {
              "type": "string",
              "pattern" : "[ncC]\\.\\S+"
            },
            "hgvs_p": {
              "type": ["string", "null"],
              "pattern" : "[pP]\\.\\S+"
            },
            "variant_type": {
              "type": "array",
              "minItems": 1,
              "items": {"type" : "string"}
            },
            "exon": {
              "type": ["integer", "null"]
            },
            "intron": {
              "type" : ["integer", "null"]
            }
          },
          "required": [
            "transcript",
            "hgvs_c",
            "variant_type"
          ]
        }
      ]
    },
    "splicing_prediction_tools": {
      "type": "object",
      "properties": {
        "SpliceAI": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        }
      },
      "required": [
        "SpliceAI"
      ]
    },
    "pathogenicity_prediction_tools": {
      "type": "object",
      "properties": {
        "REVEL": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        },
        "BayesDel": {
          "type": "number",
          "minimum" : -1.29334,
          "maximum" : 0.75731
        }
      }
    },
    "gnomAD": {
      "type": "object",
      "properties": {
        "AF": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        },
        "AC": {
          "type": "integer",
          "minimum" : 0
        },
        "AC_hom": {
          "type": "integer",
          "minimum" : 0
        },
        "subpopulation": {
          "type": "string",
          "pattern" : "[A-Z]{3}"
        },
        "popmax_AF": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        },
        "popmax_AC": {
          "type" : "integer",
          "minimum": 0
        },
        "faf_popmax_AF": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        }
      },
      "required": [
        "AF",
        "AC",
        "subpopulation",
        "popmax_AF",
        "popmax_AC",
        "faf_popmax_AF"
      ]
    },
    "FLOSSIES": {
      "type": "object",
      "properties": {
        "AFR": {
          "type": "integer",
          "minimum" : 0
        },
        "EUR": {
          "type": "integer",
          "minimum" : 0
        }
      },
      "required": [
        "AFR",
        "EUR"
      ]
    },
    "cancer_hotspots": {
      "type": "object",
      "properties": {
        "AF": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        },
        "AC": {
          "type": "integer",
          "minimum" : 0
        }
      }
    },
    "mRNA_analysis": {
      "type": "array",
      "items" : [
        { "type": "object",
          "properteis" :{
            "minigene" : {
              "type": "boolean"
            },
            "patient_rna" : {
              "type": "boolean"
            },
            "allelic" : {
              "type": "str"
            },
            "quantification" :{
              "type": ["float", "null"]
            }
          },
          "required": [
            "minigene",
            "patient_rna",
            "allelic",
            "quantification"
          ]
        }
      ]
    },
    "functional_data" : {
      "type" : "array",
      "items": [
        {
        "type": "object",
        "properties": {
          "pathogenic" :{
            "type": "boolean"
          },
          "benign" : {
            "type": "boolean"
          }
        },
        "required": [
          "pathogenic",
          "benign"
        ]
      }
      ]
    },
    "prior": {
      "type": "number"
    },
    "co-occurrence": {
      "type": "number"
    },
    "segregation": {
      "type": "number"
    },
    "multifactorial_log-likelihood": {
      "type": "number"
    },
    "VUS_task_force_domain": {
      "type": "boolean"
    },
    "cold_spot" :{
      "type" : "boolean"
    }
  },
  "required": [
    "chr",
    "pos",
    "gene",
    "ref",
    "alt",
    "variant_type",
    "variant_effect",
    "cold_spot"
  ]
}

=== akatzke/HerediClassify/test/test_variants_gene_specific/PALB2_splice_donor_variant.json
{"chr": "chr16", "pos": 23637849, "gene": "PALB2", "ref": "C", "alt": "A", "variant_type": ["non_coding_transcript_variant", "NMD_transcript_variant", "splice_donor_variant", "intron_variant"], "variant_effect": [{"transcript": "ENST00000261584", "hgvs_c": "c.211+1G>T", "variant_type": ["splice_donor_variant"], "intron": 3}, {"transcript": "ENST00000561514", "hgvs_c": "c.-675+1G>T", "variant_type": ["splice_donor_variant"], "intron": 3}, {"transcript": "ENST00000565038", "hgvs_c": "c.86+1G>T", "variant_type": ["splice_donor_variant", "NMD_transcript_variant"], "intron": 1}, {"transcript": "ENST00000567003", "hgvs_c": "n.489+1G>T", "variant_type": ["splice_donor_variant", "non_coding_transcript_variant"], "intron": 4}, {"transcript": "ENST00000568219", "hgvs_c": "c.-675+1G>T", "variant_type": ["splice_donor_variant"], "intron": 3}, {"transcript": "ENST00000697374", "hgvs_c": "c.-675+1G>T", "variant_type": ["splice_donor_variant"], "intron": 3}, {"transcript": "ENST00000697375", "hgvs_c": "n.1558+1G>T", "variant_type": ["splice_donor_variant", "non_coding_transcript_variant"], "intron": 2}, {"transcript": "ENST00000697376", "hgvs_c": "c.-675+1G>T", "variant_type": ["splice_donor_variant"], "intron": 4}, {"transcript": "ENST00000697377", "hgvs_c": "c.-675+1G>T", "variant_type": ["splice_donor_variant"], "intron": 4}, {"transcript": "ENST00000697378", "hgvs_c": "n.731+1G>T", "variant_type": ["splice_donor_variant", "non_coding_transcript_variant"], "intron": 3}, {"transcript": "ENST00000697379", "hgvs_c": "c.-675+1G>T", "variant_type": ["splice_donor_variant"], "intron": 4}, {"transcript": "ENST00000697382", "hgvs_c": "c.-675+1G>T", "variant_type": ["splice_donor_variant", "NMD_transcript_variant"], "intron": 4}, {"transcript": "ENST00000697383", "hgvs_c": "c.48+3261G>T", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000697384", "hgvs_c": "n.365+1G>T", "variant_type": ["splice_donor_variant", "non_coding_transcript_variant"], "intron": 3}], "splicing_prediction_tools": {"SpliceAI": 1.0}, "pathogenicity_prediction_tools": {"BayesDel": 0.63}, "cold_spot": false}

=== akatzke/HerediClassify/test/test_variants_gene_specific/PALB2_intron_variant.json
{"chr": "chr16", "pos": 23637843, "gene": "PALB2", "ref": "G", "alt": "T", "variant_type": ["intron_variant", "NMD_transcript_variant", "splice_region_variant", "non_coding_transcript_variant"], "variant_effect": [{"transcript": "ENST00000261584", "hgvs_c": "c.211+7C>A", "variant_type": ["splice_region_variant", "intron_variant"], "intron": 3}, {"transcript": "ENST00000561514", "hgvs_c": "c.-675+7C>A", "variant_type": ["splice_region_variant", "intron_variant"], "intron": 3}, {"transcript": "ENST00000565038", "hgvs_c": "c.86+7C>A", "variant_type": ["splice_region_variant", "intron_variant", "NMD_transcript_variant"], "intron": 1}, {"transcript": "ENST00000567003", "hgvs_c": "n.489+7C>A", "variant_type": ["splice_region_variant", "intron_variant", "non_coding_transcript_variant"], "intron": 4}, {"transcript": "ENST00000568219", "hgvs_c": "c.-675+7C>A", "variant_type": ["splice_region_variant", "intron_variant"], "intron": 3}, {"transcript": "ENST00000697374", "hgvs_c": "c.-675+7C>A", "variant_type": ["splice_region_variant", "intron_variant"], "intron": 3}, {"transcript": "ENST00000697375", "hgvs_c": "n.1558+7C>A", "variant_type": ["splice_region_variant", "intron_variant", "non_coding_transcript_variant"], "intron": 2}, {"transcript": "ENST00000697376", "hgvs_c": "c.-675+7C>A", "variant_type": ["splice_region_variant", "intron_variant"], "intron": 4}, {"transcript": "ENST00000697377", "hgvs_c": "c.-675+7C>A", "variant_type": ["splice_region_variant", "intron_variant"], "intron": 4}, {"transcript": "ENST00000697378", "hgvs_c": "n.731+7C>A", "variant_type": ["splice_region_variant", "intron_variant", "non_coding_transcript_variant"], "intron": 3}, {"transcript": "ENST00000697379", "hgvs_c": "c.-675+7C>A", "variant_type": ["splice_region_variant", "intron_variant"], "intron": 4}, {"transcript": "ENST00000697382", "hgvs_c": "c.-675+7C>A", "variant_type": ["splice_region_variant", "intron_variant", "NMD_transcript_variant"], "intron": 4}, {"transcript": "ENST00000697383", "hgvs_c": "c.48+3267C>A", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000697384", "hgvs_c": "n.365+7C>A", "variant_type": ["splice_region_variant", "intron_variant", "non_coding_transcript_variant"], "intron": 3}], "splicing_prediction_tools": {"SpliceAI": 0.0}, "cold_spot": false}

=== akatzke/HerediClassify/test/test_variants_gene_specific/TP53_frameshift_variant_2.json
{"chr": "chr17", "pos": 7670669, "gene": "TP53", "ref": "GC", "alt": "G", "variant_type": ["frameshift_variant", "intron_variant", "NMD_transcript_variant", "3_prime_UTR_variant"], "variant_effect": [{"transcript": "ENST00000269305", "hgvs_c": "c.1039del", "hgvs_p": "p.Ala347ProfsTer23", "variant_type": ["frameshift_variant"], "exon": 10}, {"transcript": "ENST00000359597", "hgvs_c": "c.993+2865del", "variant_type": ["intron_variant"], "intron": 8}, {"transcript": "ENST00000413465", "hgvs_c": "c.782+3511del", "variant_type": ["intron_variant"], "intron": 6}, {"transcript": "ENST00000420246", "hgvs_c": "c.*146del", "variant_type": ["3_prime_UTR_variant"], "exon": 11}, {"transcript": "ENST00000445888", "hgvs_c": "c.1039del", "hgvs_p": "p.Ala347ProfsTer23", "variant_type": ["frameshift_variant"], "exon": 10}, {"transcript": "ENST00000455263", "hgvs_c": "c.*58del", "variant_type": ["3_prime_UTR_variant"], "exon": 11}, {"transcript": "ENST00000504290", "hgvs_c": "c.*58del", "variant_type": ["3_prime_UTR_variant"], "exon": 7}, {"transcript": "ENST00000504937", "hgvs_c": "c.643del", "hgvs_p": "p.Ala215ProfsTer23", "variant_type": ["frameshift_variant"], "exon": 6}, {"transcript": "ENST00000510385", "hgvs_c": "c.*146del", "variant_type": ["3_prime_UTR_variant"], "exon": 7}, {"transcript": "ENST00000576024", "hgvs_c": "c.54-980del", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000610292", "hgvs_c": "c.922del", "hgvs_p": "p.Ala308ProfsTer23", "variant_type": ["frameshift_variant"], "exon": 9}, {"transcript": "ENST00000610538", "hgvs_c": "c.*58del", "variant_type": ["3_prime_UTR_variant"], "exon": 11}, {"transcript": "ENST00000610623", "hgvs_c": "c.*58del", "variant_type": ["3_prime_UTR_variant"], "exon": 7}, {"transcript": "ENST00000618944", "hgvs_c": "c.*146del", "variant_type": ["3_prime_UTR_variant"], "exon": 7}, {"transcript": "ENST00000619186", "hgvs_c": "c.562del", "hgvs_p": "p.Ala188ProfsTer23", "variant_type": ["frameshift_variant"], "exon": 6}, {"transcript": "ENST00000619485", "hgvs_c": "c.922del", "hgvs_p": "p.Ala308ProfsTer23", "variant_type": ["frameshift_variant"], "exon": 10}, {"transcript": "ENST00000620739", "hgvs_c": "c.922del", "hgvs_p": "p.Ala308ProfsTer23", "variant_type": ["frameshift_variant"], "exon": 10}, {"transcript": "ENST00000622645", "hgvs_c": "c.*146del", "variant_type": ["3_prime_UTR_variant"], "exon": 11}, {"transcript": "ENST00000635293", "hgvs_c": "c.922del", "hgvs_p": "p.Ala308ProfsTer41", "variant_type": ["frameshift_variant", "NMD_transcript_variant"], "exon": 10}], "splicing_prediction_tools": {"SpliceAI": 0.0}, "cold_spot": false}

=== akatzke/HerediClassify/test/test_variants_gene_specific/BRCA1_stop_gained.json
{"chr": "chr17", "pos": 43045760, "gene": "BRCA1", "ref": "C", "alt": "T", "variant_type": ["NMD_transcript_variant", "3_prime_UTR_variant", "stop_gained", "non_coding_transcript_exon_variant"], "variant_effect": [{"transcript": "ENST00000352993", "hgvs_c": "c.2084G>A", "hgvs_p": "p.Trp695Ter", "variant_type": ["stop_gained"], "exon": 22}, {"transcript": "ENST00000357654", "hgvs_c": "c.5510G>A", "hgvs_p": "p.Trp1837Ter", "variant_type": ["stop_gained"], "exon": 23}, {"transcript": "ENST00000461221", "hgvs_c": "c.*5293G>A", "variant_type": ["3_prime_UTR_variant", "NMD_transcript_variant"], "exon": 23}, {"transcript": "ENST00000468300", "hgvs_c": "c.*24G>A", "variant_type": ["3_prime_UTR_variant"], "exon": 22}, {"transcript": "ENST00000471181", "hgvs_c": "c.5573G>A", "hgvs_p": "p.Trp1858Ter", "variant_type": ["stop_gained"], "exon": 24}, {"transcript": "ENST00000484087", "hgvs_c": "c.2072G>A", "hgvs_p": "p.Trp691Ter", "variant_type": ["stop_gained"], "exon": 21}, {"transcript": "ENST00000491747", "hgvs_c": "c.2198G>A", "hgvs_p": "p.Trp733Ter", "variant_type": ["stop_gained"], "exon": 23}, {"transcript": "ENST00000493795", "hgvs_c": "c.5369G>A", "hgvs_p": "p.Trp1790Ter", "variant_type": ["stop_gained"], "exon": 22}, {"transcript": "ENST00000586385", "hgvs_c": "c.440G>A", "hgvs_p": "p.Trp147Ter", "variant_type": ["stop_gained"], "exon": 8}, {"transcript": "ENST00000591534", "hgvs_c": "c.983G>A", "hgvs_p": "p.Trp328Ter", "variant_type": ["stop_gained"], "exon": 11}, {"transcript": "ENST00000591849", "hgvs_c": "c.209G>A", "hgvs_p": "p.Trp70Ter", "variant_type": ["stop_gained"], "exon": 5}, {"transcript": "ENST00000644379", "hgvs_c": "c.1898G>A", "hgvs_p": "p.Trp633Ter", "variant_type": ["stop_gained"], "exon": 15}, {"transcript": "ENST00000700081", "hgvs_c": "n.1393G>A", "variant_type": ["non_coding_transcript_exon_variant"], "exon": 3}, {"transcript": "ENST00000700082", "hgvs_c": "n.874G>A", "variant_type": ["non_coding_transcript_exon_variant"], "exon": 2}], "splicing_prediction_tools": {"SpliceAI": 0.01}, "pathogenicity_prediction_tools": {"BayesDel": 0.61701}, "cold_spot": false}

=== akatzke/HerediClassify/test/test_variants/RAD51D_start_lost.json
{"chr": "chr17", "pos": 35119612, "gene": "RAD51D", "ref": "A", "alt": "C", "variant_type": ["start_lost", "5_prime_UTR_variant", "intron_variant", "NMD_transcript_variant", "non_coding_transcript_exon_variant", "non_coding_transcript_variant"], "variant_effect": [{"transcript": "ENST00000335858", "hgvs_c": "c.2T>G", "hgvs_p": "p.Met1?", "variant_type": ["start_lost"], "exon": 1}, {"transcript": "ENST00000345365", "hgvs_c": "c.2T>G", "hgvs_p": "p.Met1?", "variant_type": ["start_lost"], "exon": 1}, {"transcript": "ENST00000394589", "hgvs_c": "c.2T>G", "hgvs_p": "p.Met1?", "variant_type": ["start_lost"], "exon": 2}, {"transcript": "ENST00000415064", "hgvs_c": "n.233-440T>G", "variant_type": ["intron_variant", "non_coding_transcript_variant"], "intron": 1}, {"transcript": "ENST00000460118", "hgvs_c": "c.-350T>G", "variant_type": ["5_prime_UTR_variant"], "exon": 1}, {"transcript": "ENST00000585947", "hgvs_c": "n.159+1679T>G", "variant_type": ["intron_variant", "non_coding_transcript_variant"], "intron": 1}, {"transcript": "ENST00000585982", "hgvs_c": "n.178-440T>G", "variant_type": ["intron_variant", "non_coding_transcript_variant"], "intron": 1}, {"transcript": "ENST00000586044", "hgvs_c": "c.2T>G", "hgvs_p": "p.Met1?", "variant_type": ["start_lost", "NMD_transcript_variant"], "exon": 1}, {"transcript": "ENST00000586210", "hgvs_c": "c.2T>G", "hgvs_p": "p.Met1?", "variant_type": ["start_lost", "NMD_transcript_variant"], "exon": 1}, {"transcript": "ENST00000587405", "hgvs_c": "c.-95+1679T>G", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000587977", "hgvs_c": "c.2T>G", "hgvs_p": "p.Met1?", "variant_type": ["start_lost", "NMD_transcript_variant"], "exon": 1}, {"transcript": "ENST00000587982", "hgvs_c": "n.191+1679T>G", "variant_type": ["intron_variant", "non_coding_transcript_variant"], "intron": 1}, {"transcript": "ENST00000588372", "hgvs_c": "c.-95+1679T>G", "variant_type": ["intron_variant", "NMD_transcript_variant"], "intron": 1}, {"transcript": "ENST00000588594", "hgvs_c": "c.2T>G", "hgvs_p": "p.Met1?", "variant_type": ["start_lost", "NMD_transcript_variant"], "exon": 1}, {"transcript": "ENST00000589506", "hgvs_c": "n.213T>G", "variant_type": ["non_coding_transcript_exon_variant"], "exon": 1}, {"transcript": "ENST00000590016", "hgvs_c": "c.2T>G", "hgvs_p": "p.Met1?", "variant_type": ["start_lost"], "exon": 1}, {"transcript": "ENST00000592430", "hgvs_c": "n.232+1679T>G", "variant_type": ["intron_variant", "non_coding_transcript_variant"], "intron": 1}, {"transcript": "ENST00000592577", "hgvs_c": "c.88+88T>G", "variant_type": ["intron_variant"], "intron": 1}], "splicing_prediction_tools": {"SpliceAI": 0.02}, "pathogenicity_prediction_tools": {"REVEL": 0.524, "BayesDel": 0.63}, "cold_spot": false}

=== akatzke/HerediClassify/test/test_variants/RAD51D_intron_variant.json
{"chr": "chr17", "pos": 35107366, "gene": "RAD51D", "ref": "C", "alt": "T", "variant_type": ["3_prime_UTR_variant", "5_prime_UTR_variant", "intron_variant", "non_coding_transcript_exon_variant", "NMD_transcript_variant", "non_coding_transcript_variant", "splice_region_variant", "synonymous_variant"], "variant_effect": [{"transcript": "ENST00000335858", "hgvs_c": "c.145-885G>A", "variant_type": ["intron_variant"], "intron": 2}, {"transcript": "ENST00000345365", "hgvs_c": "c.345G>A", "hgvs_p": "p.Gln115%1Y", "variant_type": ["splice_region_variant", "synonymous_variant"], "exon": 4}, {"transcript": "ENST00000394589", "hgvs_c": "c.345G>A", "hgvs_p": "p.Gln115%1Y", "variant_type": ["splice_region_variant", "synonymous_variant"], "exon": 5}, {"transcript": "ENST00000415064", "hgvs_c": "n.495G>A", "variant_type": ["splice_region_variant", "non_coding_transcript_exon_variant"], "exon": 4}, {"transcript": "ENST00000460118", "hgvs_c": "c.-126G>A", "variant_type": ["splice_region_variant", "5_prime_UTR_variant"], "exon": 3}, {"transcript": "ENST00000585343", "hgvs_c": "c.*167G>A", "variant_type": ["splice_region_variant", "3_prime_UTR_variant", "NMD_transcript_variant"], "exon": 4}, {"transcript": "ENST00000585947", "hgvs_c": "n.241G>A", "variant_type": ["splice_region_variant", "non_coding_transcript_exon_variant"], "exon": 2}, {"transcript": "ENST00000585982", "hgvs_c": "n.500G>A", "variant_type": ["splice_region_variant", "non_coding_transcript_exon_variant"], "exon": 4}, {"transcript": "ENST00000586044", "hgvs_c": "c.*76G>A", "variant_type": ["splice_region_variant", "3_prime_UTR_variant", "NMD_transcript_variant"], "exon": 3}, {"transcript": "ENST00000586186", "hgvs_c": "c.249G>A", "hgvs_p": "p.Gln83%1Y", "variant_type": ["splice_region_variant", "synonymous_variant"], "exon": 3}, {"transcript": "ENST00000586210", "hgvs_c": "c.264-244G>A", "variant_type": ["intron_variant", "NMD_transcript_variant"], "intron": 3}, {"transcript": "ENST00000587405", "hgvs_c": "c.-13G>A", "variant_type": ["splice_region_variant", "5_prime_UTR_variant"], "exon": 2}, {"transcript": "ENST00000587977", "hgvs_c": "c.*86-244G>A", "variant_type": ["intron_variant", "NMD_transcript_variant"], "intron": 4}, {"transcript": "ENST00000587982", "hgvs_c": "n.273G>A", "variant_type": ["splice_region_variant", "non_coding_transcript_exon_variant"], "exon": 2}, {"transcript": "ENST00000588372", "hgvs_c": "c.-13G>A", "variant_type": ["splice_region_variant", "5_prime_UTR_variant", "NMD_transcript_variant"], "exon": 2}, {"transcript": "ENST00000588594", "hgvs_c": "c.*76G>A", "variant_type": ["splice_region_variant", "3_prime_UTR_variant", "NMD_transcript_variant"], "exon": 3}, {"transcript": "ENST00000589506", "hgvs_c": "n.437G>A", "variant_type": ["non_coding_transcript_exon_variant"], "exon": 3}, {"transcript": "ENST00000590016", "hgvs_c": "c.405G>A", "hgvs_p": "p.Gln135%1Y", "variant_type": ["splice_region_variant", "synonymous_variant"], "exon": 4}, {"transcript": "ENST00000590631", "hgvs_c": "c.-51-885G>A", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000592430", "hgvs_c": "n.314G>A", "variant_type": ["splice_region_variant", "non_coding_transcript_exon_variant"], "exon": 2}, {"transcript": "ENST00000592577", "hgvs_c": "c.351G>A", "hgvs_p": "p.Gln117%1Y", "variant_type": ["splice_region_variant", "synonymous_variant"], "exon": 4}, {"transcript": "ENST00000592850", "hgvs_c": "c.*86-885G>A", "variant_type": ["intron_variant", "NMD_transcript_variant"], "intron": 3}, {"transcript": "ENST00000592928", "hgvs_c": "n.167-885G>A", "variant_type": ["intron_variant", "non_coding_transcript_variant"], "intron": 2}], "splicing_prediction_tools": {"SpliceAI": 0.9}, "cold_spot": false}

=== akatzke/HerediClassify/test/test_variants_gene_specific/PTEN_missense_variant.json
{"chr": "chr10", "pos": 87933165, "gene": "PTEN", "ref": "T", "alt": "C", "variant_type": ["NMD_transcript_variant", "3_prime_UTR_variant", "missense_variant", "non_coding_transcript_exon_variant"], "variant_effect": [{"transcript": "ENST00000371953", "hgvs_c": "c.406T>C", "hgvs_p": "p.Cys136Arg", "variant_type": ["missense_variant"], "exon": 5}, {"transcript": "ENST00000472832", "hgvs_c": "c.406T>C", "hgvs_p": "p.Cys136Arg", "variant_type": ["missense_variant"], "exon": 5}, {"transcript": "ENST00000498703", "hgvs_c": "n.232T>C", "variant_type": ["non_coding_transcript_exon_variant"], "exon": 3}, {"transcript": "ENST00000686459", "hgvs_c": "c.406T>C", "hgvs_p": "p.Cys136Arg", "variant_type": ["missense_variant", "NMD_transcript_variant"], "exon": 5}, {"transcript": "ENST00000688158", "hgvs_c": "n.1141T>C", "variant_type": ["non_coding_transcript_exon_variant"], "exon": 7}, {"transcript": "ENST00000688308", "hgvs_c": "c.406T>C", "hgvs_p": "p.Cys136Arg", "variant_type": ["missense_variant"], "exon": 6}, {"transcript": "ENST00000688922", "hgvs_c": "c.*236T>C", "variant_type": ["3_prime_UTR_variant", "NMD_transcript_variant"], "exon": 6}, {"transcript": "ENST00000693560", "hgvs_c": "c.925T>C", "hgvs_p": "p.Cys309Arg", "variant_type": ["missense_variant"], "exon": 6}, {"transcript": "ENST00000700021", "hgvs_c": "c.361T>C", "hgvs_p": "p.Cys121Arg", "variant_type": ["missense_variant"], "exon": 4}, {"transcript": "ENST00000700022", "hgvs_c": "c.406T>C", "hgvs_p": "p.Cys136Arg", "variant_type": ["missense_variant", "NMD_transcript_variant"], "exon": 5}, {"transcript": "ENST00000700029", "hgvs_c": "c.241T>C", "hgvs_p": "p.Cys81Arg", "variant_type": ["missense_variant"], "exon": 3}], "splicing_prediction_tools": {"SpliceAI": 0.01}, "pathogenicity_prediction_tools": {"REVEL": 0.991, "BayesDel": 0.598079}, "cancer_hotspots": {"AF": 0.0003713330857779428, "AC": 9}, "cold_spot": false}

=== akatzke/HerediClassify/test/test_variants/test_var_palb2_protein.json
{
    "chr" : "16",
    "pos" : 23624008,
    "gene":  "PALB2",
    "ref" : "C",
    "alt" : "T",
    "variant_type" : ["splice_donor"],
    "variant_effect" : [
        {"transcript" : "ENST00000261584",
         "hgvs_c" : "c.2834+1G>T",
         "variant_type" : ["splice_donor"],
         "intron" : 8
        }
    ],
    "splicing_prediction_tools":
        {"SpliceAI": 0.98},
    "pathogenicity_prediction_tools":
        {"REVEL" : 0.5,
         "BayesDel" : 0.5},
    "gnomAD":
        {"AF": 0.007,
         "AC" : 12,
         "subpopulation": "EAS",
         "popmax_AF" : 0.009,
         "faf_popmax_AF" : 0.009,
         "popmax_AC" : 5},
    "FLOSSIES":
        {"AFR" : 9,
         "EUR" : 130},
    "prior": 0.25,
    "co-occurrence" : 0.56,
    "segregation" : 0.56,
    "multifactorial_log-likelihood": 0.56,
    "VUS_task_force_domain" : true,
    "cold_spot": true
}
