=== akatzke/HerediClassify/API/schema_input.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "chr": {
      "type": "string"
    },
    "pos": {
      "type": "integer"
    },
    "gene": {
      "type": "string"
    },
    "ref": {
      "type": "string"
    },
    "alt": {
      "type": "string"
    },
    "variant_type": {
      "type": "array",
      "minItems" : 1,
      "items": {"type" : "string"}
    },
    "variant_effect": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "transcript": {
              "type": "string",
              "pattern" : "ENST[0-9]{5,15}"
            },
            "hgvs_c": {
              "type": "string",
              "pattern" : "[ncC]\\.\\S+"
            },
            "hgvs_p": {
              "type": ["string", "null"],
              "pattern" : "[pP]\\.\\S+"
            },
            "variant_type": {
              "type": "array",
              "minItems": 1,
              "items": {"type" : "string"}
            },
            "exon": {
              "type": ["integer", "null"]
            },
            "intron": {
              "type" : ["integer", "null"]
            }
          },
          "required": [
            "transcript",
            "hgvs_c",
            "variant_type"
          ]
        }
      ]
    },
    "splicing_prediction_tools": {
      "type": "object",
      "properties": {
        "SpliceAI": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        }
      },
      "required": [
        "SpliceAI"
      ]
    },
    "pathogenicity_prediction_tools": {
      "type": "object",
      "properties": {
        "REVEL": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        },
        "BayesDel": {
          "type": "number",
          "minimum" : -1.29334,
          "maximum" : 0.75731
        }
      }
    },
    "gnomAD": {
      "type": "object",
      "properties": {
        "AF": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        },
        "AC": {
          "type": "integer",
          "minimum" : 0
        },
        "AC_hom": {
          "type": "integer",
          "minimum" : 0
        },
        "subpopulation": {
          "type": "string",
          "pattern" : "[A-Z]{3}"
        },
        "popmax_AF": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        },
        "popmax_AC": {
          "type" : "integer",
          "minimum": 0
        },
        "faf_popmax_AF": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        }
      },
      "required": [
        "AF",
        "AC",
        "subpopulation",
        "popmax_AF",
        "popmax_AC",
        "faf_popmax_AF"
      ]
    },
    "FLOSSIES": {
      "type": "object",
      "properties": {
        "AFR": {
          "type": "integer",
          "minimum" : 0
        },
        "EUR": {
          "type": "integer",
          "minimum" : 0
        }
      },
      "required": [
        "AFR",
        "EUR"
      ]
    },
    "cancer_hotspots": {
      "type": "object",
      "properties": {
        "AF": {
          "type": "number",
          "minimum" : 0,
          "maximum" : 1
        },
        "AC": {
          "type": "integer",
          "minimum" : 0
        }
      }
    },
    "mRNA_analysis": {
      "type": "array",
      "items" : [
        { "type": "object",
          "properteis" :{
            "minigene" : {
              "type": "boolean"
            },
            "patient_rna" : {
              "type": "boolean"
            },
            "allelic" : {
              "type": "str"
            },
            "quantification" :{
              "type": ["float", "null"]
            }
          },
          "required": [
            "minigene",
            "patient_rna",
            "allelic",
            "quantification"
          ]
        }
      ]
    },
    "functional_data" : {
      "type" : "array",
      "items": [
        {
        "type": "object",
        "properties": {
          "pathogenic" :{
            "type": "boolean"
          },
          "benign" : {
            "type": "boolean"
          }
        },
        "required": [
          "pathogenic",
          "benign"
        ]
      }
      ]
    },
    "prior": {
      "type": "number"
    },
    "co-occurrence": {
      "type": "number"
    },
    "segregation": {
      "type": "number"
    },
    "multifactorial_log-likelihood": {
      "type": "number"
    },
    "VUS_task_force_domain": {
      "type": "boolean"
    },
    "cold_spot" :{
      "type" : "boolean"
    }
  },
  "required": [
    "chr",
    "pos",
    "gene",
    "ref",
    "alt",
    "variant_type",
    "variant_effect",
    "cold_spot"
  ]
}

=== akatzke/HerediClassify/test/test_variants/BRCA1_frameshift_variant.json
{"chr": "chr17",
	"pos": 43104232,
	"gene": "BRCA1",
	"ref": "A",
	"alt":"AT",
	"variant_type": ["frameshift_variant"],
	"variant_effect": [{"transcript": "ENST00000357654", "hgvs_c": "c.330_331insA", "variant_type": ["frameshift_variant"], "exon": 6}],
	"splicing_prediction_tools": {"SpliceAI": 0.0},
       	"gnomAD": {"AF": 0.000624179, "AC": 95, "subpopulation": "AMR", "popmax_AC": 12, "popmax_AF": 0.000785649, "faf_popmax_AF": 0.000785649},
	"cold_spot": false}

=== akatzke/HerediClassify/test/test_variants_gene_specific/BRCA1_synonymous_variant.json
{"chr": "chr17", "pos": 43045720, "gene": "BRCA1", "ref": "C", "alt": "T", "variant_type": ["synonymous_variant", "3_prime_UTR_variant", "non_coding_transcript_exon_variant", "NMD_transcript_variant"], "variant_effect": [{"transcript": "ENST00000352993", "hgvs_c": "c.2124G>A", "hgvs_p": "p.Leu708%1Y", "variant_type": ["synonymous_variant"], "exon": 22}, {"transcript": "ENST00000357654", "hgvs_c": "c.5550G>A", "hgvs_p": "p.Leu1850%1Y", "variant_type": ["synonymous_variant"], "exon": 23}, {"transcript": "ENST00000461221", "hgvs_c": "c.*5333G>A", "variant_type": ["3_prime_UTR_variant", "NMD_transcript_variant"], "exon": 23}, {"transcript": "ENST00000468300", "hgvs_c": "c.*64G>A", "variant_type": ["3_prime_UTR_variant"], "exon": 22}, {"transcript": "ENST00000471181", "hgvs_c": "c.5613G>A", "hgvs_p": "p.Leu1871%1Y", "variant_type": ["synonymous_variant"], "exon": 24}, {"transcript": "ENST00000484087", "hgvs_c": "c.2112G>A", "hgvs_p": "p.Leu704%1Y", "variant_type": ["synonymous_variant"], "exon": 21}, {"transcript": "ENST00000491747", "hgvs_c": "c.2238G>A", "hgvs_p": "p.Leu746%1Y", "variant_type": ["synonymous_variant"], "exon": 23}, {"transcript": "ENST00000493795", "hgvs_c": "c.5409G>A", "hgvs_p": "p.Leu1803%1Y", "variant_type": ["synonymous_variant"], "exon": 22}, {"transcript": "ENST00000586385", "hgvs_c": "c.480G>A", "hgvs_p": "p.Leu160%1Y", "variant_type": ["synonymous_variant"], "exon": 8}, {"transcript": "ENST00000591534", "hgvs_c": "c.1023G>A", "hgvs_p": "p.Leu341%1Y", "variant_type": ["synonymous_variant"], "exon": 11}, {"transcript": "ENST00000591849", "hgvs_c": "c.249G>A", "hgvs_p": "p.Leu83%1Y", "variant_type": ["synonymous_variant"], "exon": 5}, {"transcript": "ENST00000644379", "hgvs_c": "c.1938G>A", "hgvs_p": "p.Leu646%1Y", "variant_type": ["synonymous_variant"], "exon": 15}, {"transcript": "ENST00000700081", "hgvs_c": "n.1433G>A", "variant_type": ["non_coding_transcript_exon_variant"], "exon": 3}, {"transcript": "ENST00000700082", "hgvs_c": "n.914G>A", "variant_type": ["non_coding_transcript_exon_variant"], "exon": 2}], "splicing_prediction_tools": {"SpliceAI": 0.0}, "cold_spot": false}

=== akatzke/HerediClassify/API/example_input.json
{
    "chr" : "17",
    "pos" : 43057110,
    "gene":  "BRCA1",
    "ref" : "A",
    "alt" : "C",
    "variant_type" : ["missense_variant"],
    "variant_effect" : [
        {"transcript" : "ENST00000357654",
         "hgvs_c" : "c.5219T>G",
         "hgvs_p" : "p.Val1740Gly",
         "variant_type" : ["missense_variant"],
         "exon" : 19
         },
        {"transcript" : "ENST00000471181",
         "hgvs_c" : "c.5282T>G",
         "hgvs_p" : "p.Val1761Gly",
         "variant_type" : ["missense_variant"],
         "exon" : 20
        }
    ],
    "splicing_prediction_tools":
        {"SpliceAI": 0.5},
    "pathogenicity_prediction_tools":
        {"REVEL" : 0.5,
         "BayesDel" : 0.5},
    "gnomAD":
        {"AF": 0.007,
         "AC" : 12,
         "AC_hom" : 1,
         "subpopulation": "EAS",
         "popmax_AF" : 0.009,
         "popmax_AC" : 5,
         "faf_popmax_AF" : 0.005
         },
    "FLOSSIES":
        {"AFR" : 9,
         "EUR" : 130},
    "cancer_hotspots":
        {"AF" : 0.000041,
         "AC": 1},
    "mRNA_analysis" : [
        {"minigene": true,
         "patient_rna": false,
         "allelic" : "Construct",
         "quantification": null}
        ],
    "functional_data": [

        {"pathogenic": false,
         "benign": true},
        {"pathogenic": false,
         "benign": true}
        ],
    "prior": 0.25,
    "co-occurrence" : 0.56,
    "segregation" : 0.56,
    "multifactorial_log-likelihood": 0.56,
    "VUS_task_force_domain" : true,
    "cold_spot": true
}

=== akatzke/HerediClassify/test/test_variants/CHEK2_stop_gained.json
{"chr": "chr22",
 "pos": 28687961,
 "gene": "CHEK2",
 "ref": "CG",
 "alt": "C",
 "variant_type": ["NMD_transcript_variant", "non_coding_transcript_exon_variant", "stop_gained", "frameshift_variant", "3_prime_UTR_variant"],
 "variant_effect":
 [{"transcript": "ENST00000404276", "hgvs_c": "c.1567del", "variant_type": ["frameshift_variant"], "exon": 10}],
 "splicing_prediction_tools": {"SpliceAI": 0.0},
 "pathogenicity_prediction_tools": {},
 "gnomAD": {"AF": 1.97182e-05, "AC": 3, "subpopulation": "EAS", "popmax_AC": 1, "popmax_AF": 0.000192604, "faf_popmax_AF": 0.0},
 "cancer_hotspots": {},
 "cold_spot": false}

=== akatzke/HerediClassify/test/test_variants_gene_specific/BRCA1_missense_variant.json
{"chr": "chr17", "pos": 43092418, "gene": "BRCA1", "ref": "T", "alt": "C", "variant_type": ["intron_variant", "missense_variant", "3_prime_UTR_variant", "NMD_transcript_variant"], "variant_effect": [{"transcript": "ENST00000352993", "hgvs_c": "c.671-1386A>G", "variant_type": ["intron_variant"], "intron": 9}, {"transcript": "ENST00000354071", "hgvs_c": "c.3113A>G", "hgvs_p": "p.Glu1038Gly", "variant_type": ["missense_variant"], "exon": 10}, {"transcript": "ENST00000357654", "hgvs_c": "c.3113A>G", "hgvs_p": "p.Glu1038Gly", "variant_type": ["missense_variant"], "exon": 10}, {"transcript": "ENST00000461221", "hgvs_c": "c.*2896A>G", "variant_type": ["3_prime_UTR_variant", "NMD_transcript_variant"], "exon": 10}, {"transcript": "ENST00000468300", "hgvs_c": "c.788-1386A>G", "variant_type": ["intron_variant"], "intron": 10}, {"transcript": "ENST00000471181", "hgvs_c": "c.3113A>G", "hgvs_p": "p.Glu1038Gly", "variant_type": ["missense_variant"], "exon": 10}, {"transcript": "ENST00000478531", "hgvs_c": "c.785-1386A>G", "variant_type": ["intron_variant"], "intron": 10}, {"transcript": "ENST00000484087", "hgvs_c": "c.665-1386A>G", "variant_type": ["intron_variant"], "intron": 8}, {"transcript": "ENST00000491747", "hgvs_c": "c.788-1386A>G", "variant_type": ["intron_variant"], "intron": 10}, {"transcript": "ENST00000493795", "hgvs_c": "c.2972A>G", "hgvs_p": "p.Glu991Gly", "variant_type": ["missense_variant"], "exon": 9}, {"transcript": "ENST00000493919", "hgvs_c": "c.647-1386A>G", "variant_type": ["intron_variant"], "intron": 9}, {"transcript": "ENST00000586385", "hgvs_c": "c.5-28467A>G", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000591534", "hgvs_c": "c.-43-17897A>G", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000591849", "hgvs_c": "c.-99+32853A>G", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000700182", "hgvs_c": "c.707-1386A>G", "variant_type": ["intron_variant"], "intron": 9}], "splicing_prediction_tools": {"SpliceAI": 0.0}, "pathogenicity_prediction_tools": {"REVEL": 0.227, "BayesDel": -0.307134}, "gnomAD": {"AF": 0.300299, "AC": 45583, "subpopulation": "SAS", "popmax_AC": 2368, "popmax_AF": 0.492717, "faf_popmax_AF": 0.492717}, "FLOSSIES": {"AFR": 828, "EUR": 3985}, "cold_spot": false}

=== akatzke/HerediClassify/test/test_variants_gene_specific/TP53_splice_donor_variant.json
{"chr": "chr17", "pos": 7673700, "gene": "TP53", "ref": "C", "alt": "T", "variant_type": ["intron_variant", "splice_donor_variant", "NMD_transcript_variant"], "variant_effect": [{"transcript": "ENST00000269305", "hgvs_c": "c.919+1G>A", "variant_type": ["splice_donor_variant"], "intron": 8}, {"transcript": "ENST00000359597", "hgvs_c": "c.919+1G>A", "variant_type": ["splice_donor_variant"], "intron": 7}, {"transcript": "ENST00000413465", "hgvs_c": "c.782+481G>A", "variant_type": ["intron_variant"], "intron": 6}, {"transcript": "ENST00000420246", "hgvs_c": "c.919+1G>A", "variant_type": ["splice_donor_variant"], "intron": 8}, {"transcript": "ENST00000445888", "hgvs_c": "c.919+1G>A", "variant_type": ["splice_donor_variant"], "intron": 8}, {"transcript": "ENST00000455263", "hgvs_c": "c.919+1G>A", "variant_type": ["splice_donor_variant"], "intron": 8}, {"transcript": "ENST00000504290", "hgvs_c": "c.523+1G>A", "variant_type": ["splice_donor_variant"], "intron": 4}, {"transcript": "ENST00000504937", "hgvs_c": "c.523+1G>A", "variant_type": ["splice_donor_variant"], "intron": 4}, {"transcript": "ENST00000509690", "hgvs_c": "c.523+1G>A", "variant_type": ["splice_donor_variant"], "intron": 5}, {"transcript": "ENST00000510385", "hgvs_c": "c.523+1G>A", "variant_type": ["splice_donor_variant"], "intron": 4}, {"transcript": "ENST00000610292", "hgvs_c": "c.802+1G>A", "variant_type": ["splice_donor_variant"], "intron": 7}, {"transcript": "ENST00000610538", "hgvs_c": "c.802+1G>A", "variant_type": ["splice_donor_variant"], "intron": 8}, {"transcript": "ENST00000610623", "hgvs_c": "c.442+1G>A", "variant_type": ["splice_donor_variant"], "intron": 4}, {"transcript": "ENST00000618944", "hgvs_c": "c.442+1G>A", "variant_type": ["splice_donor_variant"], "intron": 4}, {"transcript": "ENST00000619186", "hgvs_c": "c.442+1G>A", "variant_type": ["splice_donor_variant"], "intron": 4}, {"transcript": "ENST00000619485", "hgvs_c": "c.802+1G>A", "variant_type": ["splice_donor_variant"], "intron": 8}, {"transcript": "ENST00000620739", "hgvs_c": "c.802+1G>A", "variant_type": ["splice_donor_variant"], "intron": 8}, {"transcript": "ENST00000622645", "hgvs_c": "c.802+1G>A", "variant_type": ["splice_donor_variant"], "intron": 8}, {"transcript": "ENST00000635293", "hgvs_c": "c.802+1G>A", "variant_type": ["splice_donor_variant", "NMD_transcript_variant"], "intron": 8}], "splicing_prediction_tools": {"SpliceAI": 0.99}, "pathogenicity_prediction_tools": {"BayesDel": 0.66}, "cancer_hotspots": {"AF": 0.00041259231753104755, "AC": 10}, "cold_spot": false}

=== akatzke/HerediClassify/test/test_variants/BRCA1_missense_variant.json
{"chr": "chr17", "pos": 43082529, "gene": "BRCA1", "ref": "A", "alt": "G", "variant_type": ["intron_variant", "NMD_transcript_variant", "non_coding_transcript_exon_variant", "missense_variant", "3_prime_UTR_variant"], "variant_effect": [{"transcript": "ENST00000497488", "hgvs_c": "c.3344T>C", "hgvs_p": "p.Met1115Thr", "variant_type": ["missense_variant"], "exon": 4}, {"transcript": "ENST00000489037", "hgvs_c": "c.4154T>C", "hgvs_p": "p.Met1385Thr", "variant_type": ["missense_variant"], "exon": 11}, {"transcript": "ENST00000478531", "hgvs_c": "c.920T>C", "hgvs_p": "p.Met307Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000357654", "hgvs_c": "c.4232T>C", "hgvs_p": "p.Met1411Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000473961", "hgvs_c": "c.4106T>C", "hgvs_p": "p.Met1369Thr", "variant_type": ["missense_variant"], "exon": 10}, {"transcript": "ENST00000477152", "hgvs_c": "c.4154T>C", "hgvs_p": "p.Met1385Thr", "variant_type": ["missense_variant"], "exon": 11}, {"transcript": "ENST00000352993", "hgvs_c": "c.806T>C", "hgvs_p": "p.Met269Thr", "variant_type": ["missense_variant"], "exon": 11}, {"transcript": "ENST00000493919", "hgvs_c": "c.782T>C", "hgvs_p": "p.Met261Thr", "variant_type": ["missense_variant"], "exon": 11}, {"transcript": "ENST00000494123", "hgvs_c": "c.4232T>C", "hgvs_p": "p.Met1411Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000471181", "hgvs_c": "c.4232T>C", "hgvs_p": "p.Met1411Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000652672", "hgvs_c": "c.4091T>C", "hgvs_p": "p.Met1364Thr", "variant_type": ["missense_variant"], "exon": 13}, {"transcript": "ENST00000634433", "hgvs_c": "c.4109T>C", "hgvs_p": "p.Met1370Thr", "variant_type": ["missense_variant"], "exon": 10}, {"transcript": "ENST00000476777", "hgvs_c": "c.4226T>C", "hgvs_p": "p.Met1409Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000470026", "hgvs_c": "c.4232T>C", "hgvs_p": "p.Met1411Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000618469", "hgvs_c": "c.4232T>C", "hgvs_p": "p.Met1411Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000461574", "hgvs_c": "c.4232T>C", "hgvs_p": "p.Met1411Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000644555", "hgvs_c": "c.782T>C", "hgvs_p": "p.Met261Thr", "variant_type": ["missense_variant"], "exon": 13}, {"transcript": "ENST00000468300", "hgvs_c": "c.923T>C", "hgvs_p": "p.Met308Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000644379", "hgvs_c": "c.4232T>C", "hgvs_p": "p.Met1411Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000484087", "hgvs_c": "c.797T>C", "hgvs_p": "p.Met266Thr", "variant_type": ["missense_variant"], "exon": 10}, {"transcript": "ENST00000586385", "hgvs_c": "c.5-18578T>C", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000591534", "hgvs_c": "c.-43-8008T>C", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000591849", "hgvs_c": "c.-98-32339T>C", "variant_type": ["intron_variant"], "intron": 1}, {"transcript": "ENST00000493795", "hgvs_c": "c.4091T>C", "hgvs_p": "p.Met1364Thr", "variant_type": ["missense_variant"], "exon": 11}, {"transcript": "ENST00000461221", "hgvs_c": "c.*4015T>C", "variant_type": ["3_prime_UTR_variant", "NMD_transcript_variant"], "exon": 12}, {"transcript": "ENST00000491747", "hgvs_c": "c.923T>C", "hgvs_p": "p.Met308Thr", "variant_type": ["missense_variant"], "exon": 12}, {"transcript": "ENST00000700182", "hgvs_c": "c.842T>C", "hgvs_p": "p.Met281Thr", "variant_type": ["missense_variant"], "exon": 11}, {"transcript": "ENST00000621897", "hgvs_c": "n.126T>C", "variant_type": ["non_coding_transcript_exon_variant"], "exon": 2}], "splicing_prediction_tools": {"SpliceAI": 0.0}, "pathogenicity_prediction_tools": {"REVEL": 0.228, "BayesDel": 0.0148572}, "cancer_hotspots": {}, "cold_spot": false, "functional_data": [{"benign": false, "pathogenic": false}]}

=== akatzke/HerediClassify/test/test_variants/test_var_inframe_deletion.json
{
    "chr" : "17",
    "pos" : 7676080,
    "gene":  "TP53",
    "ref" : "CAGA",
    "alt" : "C",
    "variant_type" : ["inframe_deletion"],
    "variant_effect" : [
        {"transcript" : "ENST00000269305",
         "hgvs_c" : "c.286_288del",
         "hgvs_p" : "p.Ser96del",
         "variant_type" : ["inframe_deletion"],
         "exon" : 4
         },
        {"transcript" : "ENST00000445888",
         "hgvs_c" : "c.286_288del",
         "hgvs_p" : "p.96del",
         "variant_type" : ["inframe_deletion"],
         "exon" : 4
        }
    ],
    "splicing_prediction_tools":
        {"SpliceAI": 0.5},
    "pathogenicity_prediction_tools":
        {"REVEL" : 0.5,
         "BayesDel" : 0.5},
    "gnomAD":
        {"AF": 0.007,
         "AC" : 12,
         "subpopulation": "EAS",
         "popmax_AF" : 0.009,
         "faf_popmax_AF" : 0.009,
         "popmax_AC" : 5},
    "FLOSSIES":
        {"AFR" : 9,
         "EUR" : 130},
    "prior": 0.25,
    "co-occurrence" : 0.56,
    "segregation" : 0.56,
    "multifactorial_log-likelihood": 0.56,
    "VUS_task_force_domain" : true,
    "cold_spot": true
}
